### ISSUE TITLE
Sample Trinkets overwrite project

### ISSUE THREAD

**Issue by rik-cross** [astro-pi/beta-testing#22]
Clicking the sample Trinket code below the Sense HAT Trinket causes any code written to be replaced by the example code (without warning).

I guess possible fixes are:
- Give a warning message before overwriting project code;
- Open the example in a new window.

**Comment by davidhoness** [comment]
Or maybe add it to the undo buffer

**Comment by eah13** [comment]
Thanks for reporting- this is fixed!  We went with a solution like @davidhoness suggested.  The replacement of code is now undo-able via the browser's undo functionality, just like any other edit.  This is not messaged to the user to keep the interface from being verbose but a second draft could add messaging around undo-ability or perhaps an undo button.

Closing this as fixed but please continue to drop feedback here if you think the fix is inadequate
