### ISSUE TITLE
Emulator hangs Firefox 48.0

### ISSUE THREAD

**Issue by SlowZoneDweller** [astro-pi/beta-testing#30]
The emulator embedded in the Raspberry Pi article [https://www.raspberrypi.org/blog/sense-hat-emulator/](https://www.raspberrypi.org/blog/sense-hat-emulator/) consistently locks up Firefox 48.0.

Page loads, this code is displayed in the emulator:

```
from sense_hat import SenseHat

sense = SenseHat()
red = (255, 0, 0)
sense.show_message("How cool is this?", text_colour = red)
```

When I click on the Run arrow, the graphic representation of the Sense HAT appears but then the Windows cursor changes to the spinning 'Busy' icon. The Firefox window title bar and the corresponding Task Manager entry change to "Not responding". I have to end the process to recover. Everything works as expected using Internet Explorer version 11.0.9600.18427 on the same laptop, except that the SenseHAT image is small and truncated by the top border of the window (see [this screen grab](https://thefloatingworld.smugmug.com/Image-Bank/n-8gvrW4/i-jLTpBVF/A)).

**System specs:**
Windows 8.1 64-bit, fully patched
Intel Core i7-4500U CPU
16GB RAM
Firefox 48.0

**Browser extensions:**
Google Analytics Opt-out Browser Add-on
OneTab
Video DownloadHelper
Youtube Best Video Downloader 2

**Browser plugins (all up-to-date):**
OpenH264 Video Codec provided by Cisco Systems, Inc
Primetime Content Decryption Module provided by Adobe Systems, Incorporated
Shockwave Flash 22.0 r0
VLC Web Plugin
Widevine Content Decryption Module provided by Google Inc.
Adobe Acrobat
Microsoft Office 2013

**Comment by eah13** [comment]
Thanks for the detailed report, especially the plugins.  Will try to get on a Windows box to replicate soon.

@SlowZoneDweller Are your extensions etc turned off in Private Browsing mode?  Could you try to replicate in that mode as well?  FF on windows hasn't had problems like this before so I'm going to see if I can dig in to whether it's a plugin or privacy setting thing we need to work around.

**Comment by SlowZoneDweller** [comment]
Same thing happens with Private Browsing. So I created a new temporary Windows user account, with no Firefox extensions and all plug-ins disabled. Firefox still hung when I ran the emulator, but I left it alone and, despite being labelled "Not responding", after about 2 minutes and 20 seconds the first column of the scrolling text appeared. Nothing happened after a further 3 minutes so I left it for about 25 minutes, and when I returned the second column had appeared. Left it another hour - no further activity occurred. All this time, Task Manager reported that CPU load was a virtually constant 19%-20%, but when I finally killed the Firefox process, CPU load dropped back to 1%. So the emulator definitely seems to be churning away trying to do _something_.

Here are screen captures of:

**The SenseHAT at 2m20s**
![sensehat after 2m20s](https://cloud.githubusercontent.com/assets/11727167/17602778/07050cc6-6006-11e6-8379-fca5287bca5f.jpg)

**The SenseHAT at 28m45s**
![sensehatafter 28m45s](https://cloud.githubusercontent.com/assets/11727167/17602787/16f0e484-6006-11e6-9c8f-f408527dc9cb.jpg)

**CPU load with Firefox running**
![cpu load with firefox running](https://cloud.githubusercontent.com/assets/11727167/17602808/2c23e5fe-6006-11e6-9597-0a0cb281ddd2.jpg)

**CPU load with Firefox terminated**
![cpu load with firefox terminated](https://cloud.githubusercontent.com/assets/11727167/17602813/3141d91a-6006-11e6-8438-66f5a35b4565.jpg)

**The Windows Error Report associated with the hang event in the Event Log:**
[Report.wer.txt](https://github.com/astro-pi/beta-testing/files/414097/Report.wer.txt)

Hope all that helps!

**Comment by SlowZoneDweller** [comment]
It's your call, of course, but if mine is the only report of anything like this happening, it might be something weirdly specific to this one laptop, in which case it's probably not a profitable use of your time trying to fix it. It's just a company laptop that I happened to be using when the Raspberry Pi blog post came up.

**Comment by eah13** [comment]
@SlowZoneDweller thanks for the added detail and for helping eliminate possibilities!  

Since you've eliminated the plugin theory (nice work), the next place to look in my mind would be the enterprise privacy/security settings in Windows.  It's possible that, for instance, some OS level anti spyware/adware setting could be interfering with the iframe, causing the JS it's executing to be so slow.  We've occasionally gotten hard to reproduce reports from schools running Windows.  I imagine they're using centrally managed windows as well, so it's as good a theory as I can think of at the moment.  If we can confirm this is it we can then work around whatever is getting blocked to get things running normally again

I'd like to continue to try to debug this when you're able.  Here are some things I'd think of to try:
- Does this still hang if you visit the [iframe directly](https://trinket.io/embed/python/a402308c79)?  The security settings might limit third party iframes somehow.
- Does our [sense hat demo page](https://trinket.io/sense-hat) hang for you too? If not, more evidence it could be a cross domain thing.
- Does this [while true loop without sense_hat](https://trinket.io/embed/python/6f73183759) hang for you?  If not, we'll look into the sense_hat module specifically.
- How about [skulpt.org](http://www.skulpt.org/)? (press the run button and you should see a turtle drawing below the output).  If not but all trinket.io code does we can look into our custom setup.
- Final thought: Are there any settings you can share from your company's security/privacy setup that might be relevant to this? (Related: any other sites you've noticed work differently on the laptop?)

Thanks again!

**Comment by davidhoness** [comment]
![ff48](https://cloud.githubusercontent.com/assets/6640424/18329569/0aa901d8-754c-11e6-8fde-1db4ac454747.png)
I've managed to reproduce this on my home Windows 7 PC, (Ultimate build 7601: SP 1) on FF 48.0.2
I can verify what @SlowZoneDweller has reported above.

To answer your questions above though;
- Does this still hang if you visit the iframe directly?
  - Yes
- Does our sense hat demo page hang for you too?
  - Yes (specifically the Trinket + Pi = Love program)
- Does this while true loop without sense_hat hang for you?
  - No, it works fine
- How about skulpt.org?
  - Works fine

Interestingly this code also works fine;

``` python
import time
from sense_hat import SenseHat

sense = SenseHat()

while True:
  print(sense.humidity)
  time.sleep(.1)
```

So this makes me think it's something to do with the graphics handling of the LED matrix?

I hope this helps.

Interestingly I also discovered this program works;

``` python
import time, random
from sense_hat import SenseHat

sense = SenseHat()

while True:
  val = str(random.randint(0,9))
  val = str(0)
  print(val)
  sense.show_letter(val)
  time.sleep(.1)
```

But if you remove the `val = str(0)` and have the number written to the LED matrix constantly changing then you get the hang. @SlowZoneDweller do you see the same thing?

**Comment by eah13** [comment]
Thanks! This is very helpful. Two clues are that it seems to be tied to something in our implementation of show_message and that it's likely related to something in Windows 7/8 since I wasn't able to reproduce on 10 or other OSs. 

I will try to locate a computer with this setup. In the meantime, @davidhoness, some more things to try if you are able (taken from Mozilla troubleshooting):

### Hardware acceleration

With some graphics card and graphics driver setups, Firefox may hang when using hardware acceleration. You can try turning off hardware acceleration to see if it fixes the problem.

Click the menu button and choose Options.
Select the Advanced panel and the General tab.
Uncheck Use hardware acceleration when available.
Click the menu button and then click Exit.
Start Firefox the way you normally do.
If the problem is no longer happening, then hardware acceleration was likely the cause. You can try updating your graphics drivers to see if that fixes it or simply run without hardware acceleration

### Windows Compatibility mode (don't know if this applies to FF 48)

Firefox can cause excessive CPU usage if it's set to run in compatibility mode for an older version of Windows. To fix the problem, right-click on the Firefox icon you click to start Firefox, click Properties, click the Compatibility tab, make sure the check box under Compatibility mode is unchecked, and restart Firefox. (Or if it's unchecked, try checking it)

These are kind of shots in the dark, and should be causing more problems if they're the cause, but still worth a try. 

Something in our JS is doing something that the older window + /Firefox 48 combo is very inefficient at doing, likely because it's having to fall back when it can't use some feature of windows 9/10. The fixes above are stabs at making it more efficient but the real fix will be adding specific workarounds for those things once we figure out which they are. To this end: try going to `about:crashes` in Firefox and pastebin anything you find in there. I may have to step thru the JS to find it but hopefully not.

**Comment by davidhoness** [comment]
Wow, without hardware acceleration (in FF options) it works fine!
Compatibility mode was not enabled.

I tried enabling compatibility mode for Windows XP SP3, with HW acceleration, and I still got the hang.

I had a look at `about:crashes` and there were no recent ones in there, it doesn't actually crash, it just goes so slow that you can't do anything but terminate the process.

**Comment by eah13** [comment]
OK perfect.  We've got a diagnosis.  Give me a while but I think we can at least notify users with this setup that they need to turn off hardware acceleration if they're having problems.

The last piece of info that'd be great to have is whether this happens in FF 47 or below.  Assuming it's a 48 thing, so might be able to open something on bugzilla.

**Comment by eah13** [comment]
Ah, one relevant piece of info I think I'll need from both @davidhoness and @SlowZoneDweller is what your graphics cards are, bonus points for driver version info too.  That's another variable to check out in all this.  It's been awhile since I've been on Windows but I think either system info or the graphics pane in the config manager should be fine.

to try to fix this on your individual boxes (ex just leaving HW accel off) Mozilla suggests trying a driver update (oh, those were the days..) https://support.mozilla.org/en-US/kb/upgrade-graphics-drivers-use-hardware-acceleration

**Comment by davidhoness** [comment]
NVIDIA GeForce GTX 660
Driver date: 6/29/2016 (from Device Manager)
Driver version: 10.18.13.6869 (from Device Manager)
Here's what it shows under Programs and Features:
![nvidia](https://cloud.githubusercontent.com/assets/6640424/18393072/fe5ab73a-76ab-11e6-8c2b-c89ddf51c8a5.png)

I'll try a driver update and report back.

**Comment by davidhoness** [comment]
Okay I did an update;

Driver date: 8/25/2016 (from Device Manager)
Driver version: 21.21.13.7270 (from Device Manager)

![nvidia_latest](https://cloud.githubusercontent.com/assets/6640424/18394130/54e6432c-76b0-11e6-9f9e-e2a907464c98.png)

I still get the hang with HW acceleration turned on. Was worth a shot :+1:

**Comment by davidhoness** [comment]
I had to do it quickly because it self updates, but I still get the hang in Fire Fox 47 with HW acceleration on.

![ff47](https://cloud.githubusercontent.com/assets/6640424/18394586/9b11ac04-76b2-11e6-95de-683d4105da8f.png)
