### ISSUE TITLE
Friendly errors for unsupported IMU functions

### ISSUE THREAD

**Issue by davidhoness** [astro-pi/beta-testing#32]
If you attempt to use any IMU functions the following error is displayed;

```
KeyError: fusionPose on line 4 in main.py
```

Can this report that the IMU sensor is currently unsupported but we hope to offer it in a future update? I don't want the kids to think they've done something wrong and give up etc.

**Comment by ebertmi** [comment]
Should the message appear in the console output or should we show it inside an popup/notification?

**Comment by eah13** [comment]
@davidhoness all of the IMU calls should now work. If you run into any more errors please share the code and we'll track it down.  

We should work on FYI messaging as an enhancement down the line, because I then we can zoom out and see where else it would be helpful to users and make a comprehensive solution.  But it really would make the whole thing a lot more learnable to be able to inject FYIs into their experience.
